# -*- coding: utf-8 -*-
"""Faster R-CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KktAHoh9VBR-TKIr14vRAPrhU-Ad2U6G

# **# 4. WorkSpace**
"""

!nvidia-smi

# Celda 2: Inspeccionar el entorno base de Colab
import torch, sys
print("Python:", sys.version)
print("PyTorch:", torch.__version__)
print("CUDA disponible:", torch.cuda.is_available())
print("CUDA version (PyTorch):", torch.version.cuda)
print("GPU detectada:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "Ninguna")

# Celda 3: Instalar Detectron2
# Nota: esto compila extensiones C++/CUDA nativas, tarda entre 3-6 minutos. Es normal.

import torch
TORCH_VERSION = ".".join(torch.__version__.split(".")[:2])
CUDA_VERSION = torch.__version__.split("+")[-1]
print("Compilando Detectron2 para torch:", TORCH_VERSION, "/ cuda:", CUDA_VERSION)

!python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'

import os
os.environ["TORCH_CUDA_ARCH_LIST"] = "8.0"  # 8.0 = Ampere (A100). Ajustar según la GPU real.

# Celda 4: Forzar reinicio del kernel para que las nuevas librerías carguen correctamente
import os
os.kill(os.getpid(), 9)

"""# **# 4. Descargar modelo**

"""

# Celda 5: Correr DESPUÉS del reinicio del kernel
import torch, detectron2
print("PyTorch:", torch.__version__)
print("Detectron2:", detectron2.__version__)
print("CUDA disponible:", torch.cuda.is_available())

# Este comando es el diagnóstico más útil: compara PyTorch vs Detectron2 vs CUDA del sistema
!python -m detectron2.utils.collect_env

# Celda 6: Imports estándar de Detectron2 (los iremos usando en Pasos 4-8)
from detectron2 import model_zoo
from detectron2.engine import DefaultTrainer, DefaultPredictor
from detectron2.config import get_cfg
from detectron2.data.datasets import register_coco_instances
from detectron2.data import MetadataCatalog, DatasetCatalog
from detectron2.utils.visualizer import Visualizer
from detectron2.evaluation import COCOEvaluator, inference_on_dataset
from detectron2.data import build_detection_test_loader
import os, cv2, random

print("Detectron2 listo para usar ✅")

"""# **# 4. Tratamiento del Dataset**

"""

# Celda 7: Descargar el dataset (usando Colab Secrets para no exponer la API key)
from google.colab import userdata
!pip install roboflow -q

from roboflow import Roboflow


rf = Roboflow(api_key="Ik6eEYG0FuBkzGPLZSDK")
project = rf.workspace("ariels-workspace-b3hov").project("dataset_cocoa_disease_no_aug")
version = project.version(1)
dataset = version.download("coco")
"""
#Con Augmentation
rf = Roboflow(api_key="Ik6eEYG0FuBkzGPLZSDK")
project = rf.workspace("ariels-workspace-b3hov").project("dataset_cocoa_disease_aug_ahorasi")
version = project.version(1)
dataset = version.download("coco")
"""
print("Dataset descargado en:", dataset.location)

# Limpiar el JSON: eliminar la categoría fantasma (id=0) ANTES de registrar
import json, os

def clean_coco_json(json_path, output_path):
    with open(json_path) as f:
        data = json.load(f)
    data["categories"] = [c for c in data["categories"] if c["id"] != 0]
    with open(output_path, "w") as f:
        json.dump(data, f)
    return output_path

clean_paths_det = {}
for split in ["train", "valid", "test"]:
    src = os.path.join(dataset.location, split, "_annotations.coco.json")
    dst = os.path.join(dataset.location, split, "_annotations_clean.coco.json")
    clean_paths_det[split] = clean_coco_json(src, dst)

# Mapeo conocido desde tu notes.json original
id_rename_map = {
    "0": "Health",
    "1": "carmenta foraseminis",
    "2": "moniliophthora perniciosa",
    "3": "moniliophthora roreri",
    "4": "phytophthora palmivora",
}

for split in ["train", "valid", "test"]:
    path = os.path.join(dataset.location, split, "_annotations_clean.coco.json")
    with open(path) as f:
        data = json.load(f)
    for cat in data["categories"]:
        if cat["name"] in id_rename_map:
            cat["name"] = id_rename_map[cat["name"]]
    with open(path, "w") as f:
        json.dump(data, f)

print("Nombres corregidos ✅")

# Celda 8: Confirmar que la estructura sea la esperada (COCO)
import os

for split in ["train", "valid", "test"]:
    split_path = os.path.join(dataset.location, split)
    ann_path = os.path.join(split_path, "_annotations_clean.coco.json")
    n_images = len([f for f in os.listdir(split_path) if f.lower().endswith((".jpg", ".png", ".jpeg"))])
    print(f"{split}: {n_images} imágenes | ¿existe json? {os.path.exists(ann_path)}")

# Celda 9: Ver las categorías reales que quedaron en el JSON exportado
import json

with open(os.path.join(dataset.location, "train", "_annotations_clean.coco.json")) as f:
    coco_data = json.load(f)

print("Clases detectadas:")
for cat in coco_data["categories"]:
    print(f"  id={cat['id']}  name='{cat['name']}'")
print("\nTotal imágenes en train:", len(coco_data["images"]))
print("Total anotaciones en train:", len(coco_data["annotations"]))

# Celda 10: Registrar los 3 splits
from detectron2.data.datasets import register_coco_instances
from detectron2.data import MetadataCatalog, DatasetCatalog

for d in ["cacao_train_det", "cacao_valid_det", "cacao_test_det"]:
    if d in DatasetCatalog.list():
        DatasetCatalog.remove(d)
        MetadataCatalog.remove(d)

#register_coco_instances("cacao_train_det", {}, clean_paths_det["train"], os.path.join(dataset.location, "train")) Este es el train sin augmentation
register_coco_instances("cacao_train_det", {}, clean_paths_det["train"], os.path.join(dataset.location, "train"))
register_coco_instances("cacao_valid_det", {}, clean_paths_det["valid"], os.path.join(dataset.location, "valid"))
register_coco_instances("cacao_test_det", {}, clean_paths_det["test"], os.path.join(dataset.location, "test"))

print("Datasets registrados:", [d for d in DatasetCatalog.list() if d.startswith("cacao_")])

# Celda 11: Visualizar anotaciones reales para confirmar que los polígonos están correctos
import random, cv2
from detectron2.utils.visualizer import Visualizer
import matplotlib.pyplot as plt

dataset_dicts = DatasetCatalog.get("cacao_train_det")
metadata = MetadataCatalog.get("cacao_train_det")

fig, axes = plt.subplots(1, 3, figsize=(18, 6))
for ax, d in zip(axes, random.sample(dataset_dicts, 3)):
    img = cv2.imread(d["file_name"])
    visualizer = Visualizer(img[:, :, ::-1], metadata=metadata, scale=0.8)
    out = visualizer.draw_dataset_dict(d)
    ax.imshow(out.get_image())
    ax.axis("off")
plt.tight_layout()
plt.show()

"""# **# 4. Configuración del modelo**

"""

# Celda 12: Configuración base de Faster R-CNN preentrenado en COCO
from detectron2.config import get_cfg
from detectron2 import model_zoo

cfg_frcnn = get_cfg()

# Backbone: ResNet-50 FPN, 3x schedule -> buen balance velocidad/precisión para A100
cfg_frcnn.merge_from_file(model_zoo.get_config_file("COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml"))

# Pesos preentrenados en COCO (transfer learning) - descarga automática la primera vez
cfg_frcnn.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml")

print("Config base cargada desde Model Zoo ✅")

# Celda 13: Vincular los datasets registrados en el Paso 4
cfg_frcnn.DATASETS.TRAIN = ("cacao_train_det",)
cfg_frcnn.DATASETS.TEST = ("cacao_valid_det",)  # Detectron2 usa "TEST" también para validación durante entrenamiento

# CRÍTICO: 5 clases reales, NO 6 (excluye la categoría "padre" id=0 sin instancias)
cfg_frcnn.MODEL.ROI_HEADS.NUM_CLASSES = 5

print("Clases configuradas:", cfg_frcnn.MODEL.ROI_HEADS.NUM_CLASSES)

# Import explícito antes de la verificación
from detectron2.data import DatasetMapper, DatasetCatalog

dataset_dicts = DatasetCatalog.get("cacao_train_det")
max_class_id = max(ann["category_id"] for d in dataset_dicts for ann in d["annotations"])
min_class_id = min(ann["category_id"] for d in dataset_dicts for ann in d["annotations"])
print(f"Rango de índices de clase en las anotaciones: {min_class_id} a {max_class_id}")

# Celda 14: Configurar augmentations mínimas (solo resize fijo, sin aleatoriedad)
# Tamaño fijo: 640x640, igual al "Fit within 640x640" configurado en Roboflow
cfg_frcnn.INPUT.MIN_SIZE_TRAIN = (640,)
cfg_frcnn.INPUT.MAX_SIZE_TRAIN = 640
cfg_frcnn.INPUT.MIN_SIZE_TEST = 640
cfg_frcnn.INPUT.MAX_SIZE_TEST = 640

# Desactivar flip aleatorio explícitamente
cfg_frcnn.INPUT.RANDOM_FLIP = "none"

print("Augmentation desactivada. Tamaño fijo: 640")

# Celda 14b: Verificación real del size_divisibility, construyendo el backbone
from detectron2.modeling import build_backbone

backbone = build_backbone(cfg_frcnn)
divisibility = backbone.size_divisibility
print("Size divisibility real del backbone (FPN):", divisibility)

if 640 % divisibility == 0:
    print(f"{640} es múltiplo exacto de {divisibility} → SIN padding interno, la red ve exactamente 640x640 ✅")
else:
    padded_size = ((640 // divisibility) + 1) * divisibility
    print(f"{640} → padding interno hasta: {padded_size}")

# Celda 15 (corregida): acceder a la lista interna del AugmentationList
from detectron2.data import DatasetMapper

mapper = DatasetMapper(cfg_frcnn, is_train=True)
print("Tipo de mapper.augmentations:", type(mapper.augmentations))

print("\nAugmentations activas en el pipeline de entrenamiento:")
for aug in mapper.augmentations.augs:
    print(" -", aug)

# Celda 16: Configuración de batch size e imágenes por batch
cfg_frcnn.SOLVER.IMS_PER_BATCH = 8  # imágenes por iteración (batch size)

# ROI heads: cuántas propuestas de región se muestrean por imagen para entrenar la cabeza
cfg_frcnn.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 256  # default, funciona bien con dataset chico

print("Batch size configurado:", cfg_frcnn.SOLVER.IMS_PER_BATCH)

# Celda 17: Learning rate — fine-tuning conservador para 150 épocas en dataset chico
cfg_frcnn.SEED = 42
cfg_frcnn.SOLVER.BASE_LR = 0.002
cfg_frcnn.SOLVER.WARMUP_ITERS = 250
cfg_frcnn.SOLVER.WARMUP_FACTOR = 1.0 / 250
cfg_frcnn.SOLVER.WEIGHT_DECAY = 0.0001
cfg_frcnn.MODEL.BACKBONE.FREEZE_AT = 3

print("Learning rate ajustado:", cfg_frcnn.SOLVER.BASE_LR)

# Celda 18: Cálculo de iteraciones para 150 épocas
NUM_IMAGES_TRAIN = len(DatasetCatalog.get("cacao_train_det"))
EPOCHS = 150
iterations_per_epoch = NUM_IMAGES_TRAIN / cfg_frcnn.SOLVER.IMS_PER_BATCH
total_iterations = int(EPOCHS * iterations_per_epoch)
cfg_frcnn.SOLVER.MAX_ITER = total_iterations

print(f"Imágenes train: {NUM_IMAGES_TRAIN} | Iteraciones totales: {total_iterations}")
print(f"Batch size: {cfg_frcnn.SOLVER.IMS_PER_BATCH}")
print(f"Iteraciones por época: {iterations_per_epoch:.1f}")
print(f"Iteraciones totales para {EPOCHS} épocas: {total_iterations}")

# Celda 19: Steps de decaimiento del LR, proporcionales a tu MAX_ITER real
cfg_frcnn.SOLVER.STEPS = (
    int(total_iterations * 0.6),
    int(total_iterations * 0.8),
)
cfg_frcnn.SOLVER.GAMMA = 0.1  # el LR se multiplica por 0.1 en cada step

print("LR decae en las iteraciones:", cfg_frcnn.SOLVER.STEPS)

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

OUTPUT_DIR = "/content/drive/MyDrive/cacao_experiments/faster_rcnn_sin_aug_v1"
import os
os.makedirs(OUTPUT_DIR, exist_ok=True)
cfg_frcnn.OUTPUT_DIR = OUTPUT_DIR
print("Output dir:", cfg_frcnn.OUTPUT_DIR)

print("¿Existe model_best.pth?", os.path.exists(os.path.join(cfg_frcnn.OUTPUT_DIR, "model_best.pth")))

# Celda 21: Frecuencia de checkpoints
# Con MAX_ITER=19012, guardar cada 1000 iteraciones te da ~19 checkpoints
# Balance: ni tan frecuente que sature Drive, ni tan espaciado que pierdas mucho progreso
cfg_frcnn.SOLVER.CHECKPOINT_PERIOD = 1000

print("Se guardará un checkpoint cada", cfg_frcnn.SOLVER.CHECKPOINT_PERIOD, "iteraciones")
print("Total de checkpoints esperados:", cfg_frcnn.SOLVER.MAX_ITER // cfg_frcnn.SOLVER.CHECKPOINT_PERIOD)

# Trainer específico para Faster R-CNN (equivalente a CacaoTrainer, pero solo bbox)
from detectron2.engine import DefaultTrainer
from detectron2.evaluation import COCOEvaluator

class FrcnnTrainer(DefaultTrainer):
    @classmethod
    def build_evaluator(cls, cfg, dataset_name, output_folder=None):
        if output_folder is None:
            output_folder = os.path.join(cfg.OUTPUT_DIR, "eval")
            os.makedirs(output_folder, exist_ok=True)
        return COCOEvaluator(dataset_name, output_dir=output_folder)

# Celda 22/23 (Faster R-CNN): agregar los imports que faltan
from detectron2.engine.hooks import BestCheckpointer
from detectron2.checkpoint import DetectionCheckpointer

import time
print(f"🔄 Construyendo trainer @ {time.strftime('%H:%M:%S')}")
print("MAX_ITER:", cfg_frcnn.SOLVER.MAX_ITER)
print("STEPS:", cfg_frcnn.SOLVER.STEPS)
assert cfg_frcnn.SOLVER.STEPS[-1] < cfg_frcnn.SOLVER.MAX_ITER

cfg_frcnn.TEST.EVAL_PERIOD = 1000

trainer_frcnn = FrcnnTrainer(cfg_frcnn)
trainer_frcnn.resume_or_load(resume=False)
trainer_frcnn.register_hooks([
    BestCheckpointer(eval_period=cfg_frcnn.TEST.EVAL_PERIOD,
                      checkpointer=DetectionCheckpointer(trainer_frcnn.model, cfg_frcnn.OUTPUT_DIR),
                      val_metric="bbox/AP", mode="max")
])
print(f"✅ Trainer construido @ {time.strftime('%H:%M:%S')}")

# Celda 24: Resumen de configuración antes de entrenar (checklist)
print("=== RESUMEN DE CONFIGURACIÓN ===")
print("Output dir (Drive):", cfg_frcnn.OUTPUT_DIR)
print()
print("--- Batch / Dataset ---")
print("Batch size:", cfg_frcnn.SOLVER.IMS_PER_BATCH)
print("Num clases:", cfg_frcnn.MODEL.ROI_HEADS.NUM_CLASSES)
print("Tamaño imagen (train):", cfg_frcnn.INPUT.MIN_SIZE_TRAIN, "/", cfg_frcnn.INPUT.MAX_SIZE_TRAIN)
print("Tamaño imagen (test):", cfg_frcnn.INPUT.MIN_SIZE_TEST, "/", cfg_frcnn.INPUT.MAX_SIZE_TEST)
print("Random flip:", cfg_frcnn.INPUT.RANDOM_FLIP)
print()
print("--- Optimización ---")
print("SEED:", cfg_frcnn.SEED)
print("Learning rate (base):", cfg_frcnn.SOLVER.BASE_LR)
print("Weight decay:", cfg_frcnn.SOLVER.WEIGHT_DECAY)
print("Warmup iters:", cfg_frcnn.SOLVER.WARMUP_ITERS)
print("Warmup factor:", cfg_frcnn.SOLVER.WARMUP_FACTOR)
print("Freeze at (backbone):", cfg_frcnn.MODEL.BACKBONE.FREEZE_AT)
print()
print("--- Schedule ---")
print("Iteraciones totales (MAX_ITER):", cfg_frcnn.SOLVER.MAX_ITER)
print("Steps de decay (LR /10):", cfg_frcnn.SOLVER.STEPS)
print("Gamma (factor de decay):", cfg_frcnn.SOLVER.GAMMA)
print()
print("--- Checkpoints / Evaluación ---")
print("Checkpoint cada:", cfg_frcnn.SOLVER.CHECKPOINT_PERIOD, "iteraciones")
print("Eval cada:", cfg_frcnn.TEST.EVAL_PERIOD, "iteraciones")

# --- Chequeos automáticos de coherencia ---
print()
print("=== VALIDACIONES ===")
assert cfg_frcnn.SOLVER.WARMUP_ITERS < cfg_frcnn.SOLVER.STEPS[0], \
    "⚠️ Warmup termina después del primer step de decay"
assert cfg_frcnn.SOLVER.STEPS[0] < cfg_frcnn.SOLVER.STEPS[1] < cfg_frcnn.SOLVER.MAX_ITER, \
    "⚠️ Steps no están correctamente ordenados respecto a MAX_ITER"
assert cfg_frcnn.SOLVER.CHECKPOINT_PERIOD <= cfg_frcnn.SOLVER.MAX_ITER, \
    "⚠️ CHECKPOINT_PERIOD mayor que MAX_ITER, nunca vas a guardar nada"
assert cfg_frcnn.TEST.EVAL_PERIOD > 0, \
    "⚠️ EVAL_PERIOD en 0, no se va a evaluar durante el entrenamiento (BestCheckpointer no funcionará)"
print("✅ Todas las validaciones pasaron. Configuración lista para entrenar.")

"""# **# 4. Entrenamiento**

"""

# Celda 24b (temporal, sanity check para Faster R-CNN)
import copy
from detectron2.engine import DefaultTrainer

cfg_test = copy.deepcopy(cfg_frcnn)
cfg_test.OUTPUT_DIR = "/content/drive/MyDrive/cacao_experiments/faster_rcnn_aug_v1_test"
os.makedirs(cfg_test.OUTPUT_DIR, exist_ok=True)
cfg_test.SOLVER.MAX_ITER = 50
cfg_test.SOLVER.CHECKPOINT_PERIOD = 50
cfg_test.TEST.EVAL_PERIOD = 0

trainer_test = FrcnnTrainer(cfg_test)   # <-- DefaultTrainer, no CacaoTrainer
trainer_test.resume_or_load(resume=False)
trainer_test.train()

# Celda 25: Entrenamiento completo (19,012 iteraciones)
trainer_frcnn.train()

"""# **# 4. Metricas**

"""

# Celda 26: Cargar el mejor checkpoint guardado
from detectron2.engine import DefaultPredictor
import os

best_checkpoint_path = os.path.join(cfg_frcnn.OUTPUT_DIR, "model_best.pth")
print("¿Existe el mejor checkpoint?", os.path.exists(best_checkpoint_path))

cfg_frcnn.MODEL.WEIGHTS = best_checkpoint_path
cfg_frcnn.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5  # umbral de confianza para considerar una predicción válida

predictor_frcnn = DefaultPredictor(cfg_frcnn)
print("Predictor cargado con el mejor checkpoint ✅")

# Confirma primero cuál fue la iteración real elegida como "mejor"
import json
metrics_path = os.path.join(cfg_frcnn.OUTPUT_DIR, "metrics.json")
best_iter, best_ap = None, -1
with open(metrics_path) as f:
    for line in f:
        entry = json.loads(line)
        if "bbox/AP" in entry and entry["bbox/AP"] > best_ap:
            best_ap = entry["bbox/AP"]
            best_iter = entry["iteration"]
print(f"Mejor iteración: {best_iter} | bbox/AP en validación: {best_ap:.2f}")

# Convertir iteración a época equivalente
NUM_IMAGES_TRAIN = len(DatasetCatalog.get("cacao_train_det"))  # ajustar al dataset correcto (sin_aug o con_aug)
iterations_per_epoch = NUM_IMAGES_TRAIN / cfg_frcnn.SOLVER.IMS_PER_BATCH

epoca_equivalente = best_iter / iterations_per_epoch

print(f"Mejor iteración: {best_iter}")
print(f"Iteraciones por época: {iterations_per_epoch:.1f}")
print(f"Época equivalente: {epoca_equivalente:.1f}")
print(f"bbox/AP en esa iteración: {best_ap:.2f}")

from detectron2.evaluation import COCOEvaluator, inference_on_dataset
from detectron2.data import build_detection_test_loader

DATASET_TEST_NAME = "cacao_test_det"  # ⚠️ ajustar al nombre real registrado en tu DatasetCatalog
OUT_EVAL_DIR = os.path.join(cfg_frcnn.OUTPUT_DIR, "eval_final")
os.makedirs(OUT_EVAL_DIR, exist_ok=True)

evaluator = COCOEvaluator(DATASET_TEST_NAME, output_dir=OUT_EVAL_DIR)
val_loader = build_detection_test_loader(cfg_frcnn, DATASET_TEST_NAME)

results = inference_on_dataset(predictor_frcnn.model, val_loader, evaluator)
print(results)

# --- GLOBAL ---
map50_95_global = results["bbox"]["AP"] / 100     # Detectron2 reporta en escala 0-100
map50_global = results["bbox"]["AP50"] / 100

n_test_images = len(DatasetCatalog.get(DATASET_TEST_NAME))

print(f"n_test_images: {n_test_images}")
print(f"map50 (global): {map50_global:.4f}")
print(f"map50_95 (global): {map50_95_global:.4f}")

from pycocotools.coco import COCO
from pycocotools.cocoeval import COCOeval
import numpy as np
import json

pred_json_path = os.path.join(OUT_EVAL_DIR, "coco_instances_results.json")
gt_json_path = "dataset_cocoa_disease_no_aug-1/test/_annotations_clean.coco.json"  # ⚠️ el mismo que usaste para registrar el dataset de test

coco_gt = COCO(gt_json_path)
coco_dt = coco_gt.loadRes(pred_json_path)

coco_eval = COCOeval(coco_gt, coco_dt, iouType='bbox')
coco_eval.evaluate()
coco_eval.accumulate()
coco_eval.summarize()

recall_global = coco_eval.stats[8]  # AR@100, global

# Precision global: TP / (TP+FP) al punto óptimo de F1, IoU=0.5, promediado sobre clases
precision_arr = coco_eval.eval['precision'][0, :, :, 0, -1]  # [R, K] a IoU=0.5
recall_thrs = coco_eval.params.recThrs
precisions_por_clase = []
for k in range(precision_arr.shape[1]):
    p = precision_arr[:, k]
    valid = p > -1
    if valid.any():
        f1 = 2 * p[valid] * recall_thrs[valid] / (p[valid] + recall_thrs[valid] + 1e-9)
        precisions_por_clase.append(p[valid][np.argmax(f1)])
precision_global = np.mean(precisions_por_clase) if precisions_por_clase else 0.0

print(f"recall (global, AR@100): {recall_global:.4f}")
print(f"precision (global, promedio por clase @F1 óptimo): {precision_global:.4f}")

import pandas as pd

cat_ids = coco_gt.getCatIds()
cat_id_to_name = {c['id']: c['name'] for c in coco_gt.loadCats(cat_ids)}

filas_por_clase = []
for k_idx, cat_id in enumerate(cat_ids):
    name = cat_id_to_name[cat_id]

    ap50_95 = coco_eval.eval['precision'][:, :, k_idx, 0, -1]
    ap50_95 = ap50_95[ap50_95 > -1].mean() if (ap50_95 > -1).any() else 0.0

    ap50 = coco_eval.eval['precision'][0, :, k_idx, 0, -1]
    ap50_valid = ap50[ap50 > -1]
    ap50_mean = ap50_valid.mean() if ap50_valid.size > 0 else 0.0

    p_curve = coco_eval.eval['precision'][0, :, k_idx, 0, -1]
    valid = p_curve > -1
    if valid.any():
        f1_curve = 2 * p_curve[valid] * recall_thrs[valid] / (p_curve[valid] + recall_thrs[valid] + 1e-9)
        best_idx = np.argmax(f1_curve)
        prec_clase = p_curve[valid][best_idx]
        rec_clase = recall_thrs[valid][best_idx]
        f1_clase = f1_curve[best_idx]
    else:
        prec_clase = rec_clase = f1_clase = 0.0

    filas_por_clase.append({
        'class': name,
        'map50': round(ap50_mean, 4),
        'map50_95': round(ap50_95, 4),
        'precision': round(prec_clase, 4),
        'recall': round(rec_clase, 4),
        'f1': round(f1_clase, 4),
    })

df_por_clase = pd.DataFrame(filas_por_clase)
display(df_por_clase)

cat_id_to_name = {c['id']: c['name'] for c in coco_gt.loadCats(cat_ids)}

print("Nombres reales en el ground truth (con repr para ver caracteres ocultos):")
for cid, name in cat_id_to_name.items():
    print(f"  id={cid}: {repr(name)}")

# 1. Reconstruir el DataFrame desde cero (nombres originales, sin tocar)
df_por_clase = pd.DataFrame(filas_por_clase)
print("Nombres ANTES del mapeo:")
print(df_por_clase['class'].tolist())

# 2. Mapeo correcto, confirmado con los nombres reales que viste
mapeo_nombres = {
    'Carmenta foraseminis': 'C_foraseminis',
    'Healthy': 'Sano',
    'Moniliophthora perniciosa': 'M_perniciosa',
    'Moniliophthora roreri': 'M_roreri',
    'Phytophthora palmivora': 'P_palmivora',
}

df_por_clase['class'] = df_por_clase['class'].map(mapeo_nombres)

print("\n¿Quedó algún NaN?", df_por_clase['class'].isna().any())
display(df_por_clase)

import pandas as pd

filas_faster_rcnn = [
    # --- SIN AUGMENTATION ---
    {'condition': 'sin_aug', 'class': 'GLOBAL',        'test_set_cut': 'CONFIRMAR_CON_EQUIPO', 'n_test_images': 160,
     'precision': 0.7797, 'recall': 0.7625, 'map50': 0.7712, 'map50_95': 0.6635, 'source': 'cocoeval_manual', 'notes': ''},
    {'condition': 'sin_aug', 'class': 'Sano',           'test_set_cut': 'CONFIRMAR_CON_EQUIPO', 'n_test_images': 160,
     'precision': 0.9403, 'recall': 0.87, 'map50': 0.8655, 'map50_95': 0.7380, 'source': 'cocoeval_manual', 'notes': ''},
    {'condition': 'sin_aug', 'class': 'C_foraseminis',  'test_set_cut': 'CONFIRMAR_CON_EQUIPO', 'n_test_images': 160,
     'precision': 0.6500, 'recall': 0.68, 'map50': 0.6090, 'map50_95': 0.5644, 'source': 'cocoeval_manual', 'notes': ''},
    {'condition': 'sin_aug', 'class': 'M_perniciosa',   'test_set_cut': 'CONFIRMAR_CON_EQUIPO', 'n_test_images': 160,
     'precision': 0.7273, 'recall': 0.80, 'map50': 0.7180, 'map50_95': 0.6067, 'source': 'cocoeval_manual', 'notes': ''},
    {'condition': 'sin_aug', 'class': 'M_roreri',       'test_set_cut': 'CONFIRMAR_CON_EQUIPO', 'n_test_images': 160,
     'precision': 0.8750, 'recall': 0.89, 'map50': 0.8689, 'map50_95': 0.7443, 'source': 'cocoeval_manual', 'notes': ''},
    {'condition': 'sin_aug', 'class': 'P_palmivora',    'test_set_cut': 'CONFIRMAR_CON_EQUIPO', 'n_test_images': 160,
     'precision': 0.7059, 'recall': 0.85, 'map50': 0.7947, 'map50_95': 0.6641, 'source': 'cocoeval_manual', 'notes': ''},

    # --- CON AUGMENTATION ---
    {'condition': 'con_aug', 'class': 'GLOBAL',        'test_set_cut': 'CONFIRMAR_CON_EQUIPO', 'n_test_images': 204,
     'precision': 0.8987, 'recall': 0.8096, 'map50': 0.8338, 'map50_95': 0.7474, 'source': 'cocoeval_manual',
     'notes': 'Verificar si test set de 204 imgs incluye variantes de augmentation (riesgo de leakage vs sin_aug=160)'},
    {'condition': 'con_aug', 'class': 'Sano',           'test_set_cut': 'CONFIRMAR_CON_EQUIPO', 'n_test_images': 204,
     'precision': 0.9730, 'recall': 0.87, 'map50': 0.8914, 'map50_95': 0.7809, 'source': 'cocoeval_manual', 'notes': ''},
    {'condition': 'con_aug', 'class': 'C_foraseminis',  'test_set_cut': 'CONFIRMAR_CON_EQUIPO', 'n_test_images': 204,
     'precision': 0.8077, 'recall': 0.69, 'map50': 0.6661, 'map50_95': 0.6123, 'source': 'cocoeval_manual', 'notes': ''},
    {'condition': 'con_aug', 'class': 'M_perniciosa',   'test_set_cut': 'CONFIRMAR_CON_EQUIPO', 'n_test_images': 204,
     'precision': 0.9737, 'recall': 0.97, 'map50': 0.9896, 'map50_95': 0.8608, 'source': 'cocoeval_manual', 'notes': ''},
    {'condition': 'con_aug', 'class': 'M_roreri',       'test_set_cut': 'CONFIRMAR_CON_EQUIPO', 'n_test_images': 204,
     'precision': 0.9677, 'recall': 0.81, 'map50': 0.8240, 'map50_95': 0.7274, 'source': 'cocoeval_manual', 'notes': ''},
    {'condition': 'con_aug', 'class': 'P_palmivora',    'test_set_cut': 'CONFIRMAR_CON_EQUIPO', 'n_test_images': 204,
     'precision': 0.7714, 'recall': 0.87, 'map50': 0.7980, 'map50_95': 0.7555, 'source': 'cocoeval_manual', 'notes': ''},
]

df_faster_rcnn = pd.DataFrame(filas_faster_rcnn)
display(df_faster_rcnn)

from google.colab import files
df_faster_rcnn.to_csv('metrics_fastercnn.csv', index=False)
files.download('metrics_fastercnn.csv')

"""void

"""

# Evaluación real en TEST, con umbral corregido (0.05)
cfg_frcnn.MODEL.WEIGHTS = os.path.join(cfg_frcnn.OUTPUT_DIR, "model_best.pth")
cfg_frcnn.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.05
predictor_frcnn = DefaultPredictor(cfg_frcnn)

evaluator_frcnn = COCOEvaluator("cacao_test_det", output_dir=os.path.join(cfg_frcnn.OUTPUT_DIR, "eval_test"))
test_loader_frcnn = build_detection_test_loader(cfg_frcnn, "cacao_test_det")
results_frcnn = inference_on_dataset(predictor_frcnn.model, test_loader_frcnn, evaluator_frcnn)
print(results_frcnn)

# Celda 27: Evaluación COCO completa sobre el set de TEST
from detectron2.evaluation import COCOEvaluator, inference_on_dataset
from detectron2.data import build_detection_test_loader

evaluator_frcnn = COCOEvaluator("cacao_test_det", output_dir=os.path.join(cfg_frcnn.OUTPUT_DIR, "eval_test"))
test_loader_frcnn = build_detection_test_loader(cfg_frcnn, "cacao_test_det")

results_frcnn = inference_on_dataset(predictor_frcnn.model, test_loader_frcnn, evaluator_frcnn)
print(results_frcnn)

# Celda 28 (corregida): solo bbox, Faster R-CNN no tiene tarea de segmentación
map_50_95_bbox = results_frcnn["bbox"]["AP"]
map_50_bbox = results_frcnn["bbox"]["AP50"]

print(f"mAP@50-95 (bbox): {map_50_95_bbox:.3f}")
print(f"mAP@50 (bbox):    {map_50_bbox:.3f}")

# Celda 29: Calcular Precisión, Recall y F1 con matching manual a IoU=0.5
import numpy as np
from detectron2.data import DatasetCatalog, MetadataCatalog
from detectron2.structures import pairwise_iou, Boxes
import torch

IOU_THRESHOLD = 0.5

dataset_dicts = DatasetCatalog.get("cacao_test_det")
metadata = MetadataCatalog.get("cacao_test_det")
class_names = metadata.thing_classes

# Contadores globales y por clase
tp = {c: 0 for c in class_names}
fp = {c: 0 for c in class_names}
fn = {c: 0 for c in class_names}

for d in dataset_dicts:
    img = cv2.imread(d["file_name"])
    outputs = predictor_frcnn(img)
    instances = outputs["instances"].to("cpu")

    pred_boxes = instances.pred_boxes
    pred_classes = instances.pred_classes.numpy()

    gt_boxes_list = [ann["bbox"] for ann in d["annotations"]]
    gt_classes = [ann["category_id"] for ann in d["annotations"]]

    # Convertir GT de XYWH (formato COCO) a XYXY (formato Detectron2)
    gt_boxes_xyxy = []
    for box in gt_boxes_list:
        x, y, w, h = box
        gt_boxes_xyxy.append([x, y, x + w, y + h])
    gt_boxes = Boxes(torch.tensor(gt_boxes_xyxy)) if gt_boxes_xyxy else Boxes(torch.empty((0, 4)))

    matched_gt = set()

    if len(pred_boxes) > 0 and len(gt_boxes) > 0:
        ious = pairwise_iou(pred_boxes, gt_boxes)
        for pi in range(len(pred_boxes)):
            best_iou, best_gt_idx = ious[pi].max(dim=0) if len(gt_boxes) > 0 else (0, -1)
            pred_class_name = class_names[pred_classes[pi]]

            if best_iou >= IOU_THRESHOLD and best_gt_idx.item() not in matched_gt \
               and gt_classes[best_gt_idx.item()] == pred_classes[pi]:
                tp[pred_class_name] += 1
                matched_gt.add(best_gt_idx.item())
            else:
                fp[pred_class_name] += 1
    else:
        for pi in range(len(pred_boxes)):
            fp[class_names[pred_classes[pi]]] += 1

    # Todo GT no emparejado es un falso negativo
    for gi, gc in enumerate(gt_classes):
        if gi not in matched_gt:
            fn[class_names[gc]] += 1

print("Cálculo de TP/FP/FN completado ✅")

# Celda 30: ESTA es la que genera 'recalls' — no te la saltes
print(f"{'Clase':<28} {'Precisión':>10} {'Recall':>10} {'F1':>10}")
print("-" * 60)

precisions, recalls, f1s = [], [], []

for c in class_names:
    p = tp[c] / (tp[c] + fp[c]) if (tp[c] + fp[c]) > 0 else 0.0
    r = tp[c] / (tp[c] + fn[c]) if (tp[c] + fn[c]) > 0 else 0.0
    f1 = 2 * p * r / (p + r) if (p + r) > 0 else 0.0
    precisions.append(p)
    recalls.append(r)
    f1s.append(f1)
    print(f"{c:<28} {p:>10.3f} {r:>10.3f} {f1:>10.3f}")

# Celda 30b: Promedio excluyendo la categoría padre sin instancias
real_classes = [c for c in class_names if c != "CACAO-FASTER-R-CNN"]

precisions_real = [precisions[class_names.index(c)] for c in real_classes]
recalls_real = [recalls[class_names.index(c)] for c in real_classes]
f1s_real = [f1s[class_names.index(c)] for c in real_classes]

print(f"PROMEDIO (macro, solo 5 clases reales):")
print(f"Precisión: {np.mean(precisions_real):.3f}")
print(f"Recall:    {np.mean(recalls_real):.3f}")
print(f"F1-score:  {np.mean(f1s_real):.3f}")

# Celda 31: Resumen final consolidado
print("=" * 50)
print("RESUMEN FINAL - Faster R-CNN (Detectron2)")
print("=" * 50)
print(f"mAP@50-95 (segm): {map_50_95_bbox:.3f}")
print(f"mAP@50    (segm): {map_50_bbox:.3f}")
print(f"Precisión (macro): {np.mean(precisions):.3f}")
print(f"Recall    (macro): {np.mean(recalls):.3f}")
print(f"F1-score  (macro): {np.mean(f1s):.3f}")
print("=" * 50)

# Celda 32: Conteo real de instancias por clase en cada split
import json

for split in ["train", "valid", "test"]:
    with open(os.path.join(dataset.location, split, "_annotations_clean.coco.json")) as f:
        d = json.load(f)
    cat_map = {c["id"]: c["name"] for c in d["categories"]}
    counts = {}
    for ann in d["annotations"]:
        name = cat_map[ann["category_id"]]
        counts[name] = counts.get(name, 0) + 1
    print(f"--- {split} ---")
    for name, count in sorted(counts.items(), key=lambda x: -x[1]):
        print(f"  {name}: {count}")
    print()

# Celda 33: Curva de entrenamiento (loss) y validación (segm/AP) vs iteración
import json
import matplotlib.pyplot as plt

metrics_path = os.path.join(cfg_frcnn.OUTPUT_DIR, "metrics.json")

iters, losses = [], []
val_iters, val_ap = [], []

with open(metrics_path) as f:
    for line in f:
        entry = json.loads(line)
        if "total_loss" in entry:
            iters.append(entry["iteration"])
            losses.append(entry["total_loss"])
        if "segm/AP" in entry:
            val_iters.append(entry["iteration"])
            val_ap.append(entry["segm/AP"])

fig, ax1 = plt.subplots(figsize=(10, 5))

ax1.plot(iters, losses, color="tab:blue", label="Training Loss")
ax1.set_xlabel("Iteración")
ax1.set_ylabel("Total Loss", color="tab:blue")
ax1.tick_params(axis="y", labelcolor="tab:blue")

ax2 = ax1.twinx()
ax2.plot(val_iters, val_ap, color="tab:red", marker="o", label="Validation segm/AP")
ax2.set_ylabel("segm/AP (validación)", color="tab:red")
ax2.tick_params(axis="y", labelcolor="tab:red")

plt.title("Curva de entrenamiento — Faster R-CNN (Cacao)")
fig.tight_layout()
plt.savefig(os.path.join(cfg_frcnn.OUTPUT_DIR, "training_curve.png"), dpi=150)
plt.show()

# Celda 34 (corregida para Faster R-CNN): Curva Precisión-Recall por clase
from pycocotools.coco import COCO
from pycocotools.cocoeval import COCOeval
import numpy as np
import matplotlib.pyplot as plt
import os

gt_path = os.path.join(dataset.location, "test", "_annotations_clean.coco.json")
dt_path = os.path.join(cfg_frcnn.OUTPUT_DIR, "eval_test", "coco_instances_results.json")

coco_gt = COCO(gt_path)
coco_dt = coco_gt.loadRes(dt_path)

coco_eval = COCOeval(coco_gt, coco_dt, iouType="bbox")  # <-- bbox, no segm
coco_eval.evaluate()
coco_eval.accumulate()

precision_array = coco_eval.eval["precision"]  # <-- nombre consistente
recall_thresholds = np.linspace(0, 1, 101)

cat_ids = coco_gt.getCatIds()
cat_names = [coco_gt.loadCats([cid])[0]["name"] for cid in cat_ids]

plt.figure(figsize=(9, 7))
for idx, name in enumerate(cat_names):
    pr = precision_array[0, :, idx, 0, -1]  # IoU=0.5, esta clase, area=all, maxDets=100
    pr = pr[pr > -1]
    if len(pr) > 0:
        plt.plot(recall_thresholds[:len(pr)], pr, label=name)

plt.xlabel("Recall")
plt.ylabel("Precisión")
plt.title("Curva Precisión-Recall por clase (IoU=0.5) — Test set — Faster R-CNN")
plt.legend()
plt.grid(alpha=0.3)
plt.savefig(os.path.join(cfg_frcnn.OUTPUT_DIR, "pr_curve.png"), dpi=150)  # <-- cfg_frcnn, no cfg
plt.show()

# Celda 34 (corregida): renombrar para evitar el choque con la Celda 30
from pycocotools.coco import COCO
from pycocotools.cocoeval import COCOeval
import numpy as np

gt_path = os.path.join(dataset.location, "test", "_annotations_clean.coco.json")
dt_path = os.path.join(cfg_frcnn.OUTPUT_DIR, "eval_test", "coco_instances_results.json")

coco_gt = COCO(gt_path)
coco_dt = coco_gt.loadRes(dt_path)

coco_eval = COCOeval(coco_gt, coco_dt, iouType="bbox")
coco_eval.evaluate()
coco_eval.accumulate()

precision_array = coco_eval.eval["precision"]  # <-- nombre nuevo, sin choque
cat_ids = coco_gt.getCatIds()
cat_names = [coco_gt.loadCats([cid])[0]["name"] for cid in cat_ids]

# Extraer AP@0.50-95 por clase
ap5095_per_class = {}
for idx, name in enumerate(cat_names):
    pr = precision_array[:, :, idx, 0, -1]  # todos los IoU (0.50 a 0.95), esta clase
    pr = pr[pr > -1]
    ap5095_per_class[name] = pr.mean() if len(pr) > 0 else 0.0

for name, ap in sorted(ap5095_per_class.items(), key=lambda x: -x[1]):
    print(f"{name}: {ap:.3f}")

# Celda 35 (corregida): matching mutuamente exclusivo, igual que en la Celda 29
import seaborn as sns

class_names = MetadataCatalog.get("cacao_test_det").thing_classes
n = len(class_names)
conf_matrix = np.zeros((n + 1, n + 1), dtype=int)

dataset_dicts = DatasetCatalog.get("cacao_test_det")

for d in dataset_dicts:
    img = cv2.imread(d["file_name"])
    outputs = predictor_frcnn(img)
    instances = outputs["instances"].to("cpu")
    pred_boxes = instances.pred_boxes
    pred_classes = instances.pred_classes.numpy()

    gt_boxes_list = [ann["bbox"] for ann in d["annotations"]]
    gt_classes = [ann["category_id"] for ann in d["annotations"]]
    gt_boxes_xyxy = [[x, y, x + w, y + h] for x, y, w, h in gt_boxes_list]
    gt_boxes = Boxes(torch.tensor(gt_boxes_xyxy)) if gt_boxes_xyxy else Boxes(torch.empty((0, 4)))

    matched_pred = set()
    if len(gt_boxes) > 0 and len(pred_boxes) > 0:
        ious = pairwise_iou(gt_boxes, pred_boxes)
        for gi in range(len(gt_boxes)):
            available = [pi for pi in range(len(pred_boxes)) if pi not in matched_pred]
            if not available:
                conf_matrix[gt_classes[gi], n] += 1
                continue
            sub_ious = ious[gi, available]
            local_best = sub_ious.argmax().item()
            best_iou = sub_ious[local_best].item()
            best_pi = available[local_best]

            if best_iou >= 0.5:
                conf_matrix[gt_classes[gi], pred_classes[best_pi]] += 1
                matched_pred.add(best_pi)  # <-- ahora sí se excluye para los próximos GT
            else:
                conf_matrix[gt_classes[gi], n] += 1
    else:
        for gc in gt_classes:
            conf_matrix[gc, n] += 1

    for pi in range(len(pred_boxes)):
        if pi not in matched_pred:
            conf_matrix[n, pred_classes[pi]] += 1

labels = class_names + ["no detectado / fondo"]
plt.figure(figsize=(9, 8))
sns.heatmap(conf_matrix, annot=True, fmt="d", cmap="Blues", xticklabels=labels, yticklabels=labels)
plt.xlabel("Predicción")
plt.ylabel("Ground Truth")
plt.title("Matriz de confusión — Test set (IoU≥0.5)")
plt.tight_layout()
plt.savefig(os.path.join(cfg_frcnn.OUTPUT_DIR, "confusion_matrix.png"), dpi=150)
plt.show()

# Conteo de IMÁGENES distintas por clase (no instancias) en train
from collections import defaultdict
import json

with open(os.path.join(dataset.location, "train", "_annotations_clean.coco.json")) as f:
    train_json = json.load(f)

cat_map = {c["id"]: c["name"] for c in train_json["categories"]}
images_per_class = defaultdict(set)

for ann in train_json["annotations"]:
    images_per_class[cat_map[ann["category_id"]]].add(ann["image_id"])

for name, img_set in sorted(images_per_class.items(), key=lambda x: -len(x[1])):
    print(f"{name}: {len(img_set)} imágenes distintas")

# Buscar la línea del log donde se guardó el mejor checkpoint por última vez
metrics_path = os.path.join(cfg_frcnn.OUTPUT_DIR, "metrics.json")

best_iter, best_ap = None, -1
with open(metrics_path) as f:
    for line in f:
        entry = json.loads(line)
        if "bbox/AP" in entry and entry["bbox/AP"] > best_ap:
            best_ap = entry["bbox/AP"]
            best_iter = entry["iteration"]

iterations_per_epoch = 1014 / 8  # = 126.75
best_epoch = best_iter / iterations_per_epoch

print(f"Mejor iteración: {best_iter}")
print(f"Mejor bbox/AP en validación: {best_ap:.2f}")
print(f"Equivalente a la época: {best_epoch:.1f} de 150")

import json
import os
from collections import defaultdict

for split in ["train", "valid", "test"]:
    # Usar el oversampled para train, y el clean para valid y test
    filename = "_annotations_clean.coco.json" if split == "train" else "_annotations_clean.coco.json"
    filepath = os.path.join(dataset.location, split, filename)

    with open(filepath) as f:
        d = json.load(f)

    cat_map = {c["id"]: c["name"] for c in d["categories"]}

    instance_counts = defaultdict(int)          # total de anotaciones por clase
    images_per_class = defaultdict(set)         # image_ids únicos por clase

    for ann in d["annotations"]:
        name = cat_map[ann["category_id"]]
        instance_counts[name] += 1
        images_per_class[name].add(ann["image_id"])

    print(f"--- {split} ---")
    print(f"  Total imágenes en el split: {len(d['images'])}")
    print(f"  Total instancias (anotaciones): {len(d['annotations'])}")
    print()
    print(f"  {'Clase':<20} {'Instancias':>12} {'Imágenes':>10}")
    for name in sorted(instance_counts.keys(), key=lambda x: -instance_counts[x]):
        n_instances = instance_counts[name]
        n_images = len(images_per_class[name])
        print(f"  {name:<20} {n_instances:>12} {n_images:>10}")
    print()

from collections import defaultdict
import json
import os

images_per_class_total = defaultdict(set)

for split in ["train", "valid", "test"]:
    filename = "_annotations_clean.coco.json" if split == "train" else "_annotations_clean.coco.json"
    filepath = os.path.join(dataset.location, split, filename)

    with open(filepath) as f:
        split_json = json.load(f)
    cat_map = {c["id"]: c["name"] for c in split_json["categories"]}
    for ann in split_json["annotations"]:
        # usar (split, image_id) para no mezclar ids repetidos entre splits
        images_per_class_total[cat_map[ann["category_id"]]].add((split, ann["image_id"]))

for name, img_set in sorted(images_per_class_total.items(), key=lambda x: -len(x[1])):
    print(f"{name}: {len(img_set)} imágenes distintas (dataset completo)")