# -*- coding: utf-8 -*-
"""Ultimate Train

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a6RZORW6mAsbISSt1UtbgmZe6g9sjo4B

# **# 1. Instalación**
"""

!pip install roboflow
!pip install ultralytics
import os
from google.colab import drive
drive.mount('/content/drive')
"""
from roboflow import Roboflow
rf = Roboflow(api_key="Ik6eEYG0FuBkzGPLZSDK")
project = rf.workspace("ariels-workspace-b3hov").project("dataset_cocoa_disease_aug_ahorasi")
version = project.version(1)
dataset = version.download("yolov8")

"""
# Dataset — solo necesitás la versión YOLO, nada de COCO
from roboflow import Roboflow
rf = Roboflow(api_key="Ik6eEYG0FuBkzGPLZSDK")
project = rf.workspace("ariels-workspace-b3hov").project("dataset_cocoa_disease_no_aug")
version = project.version(1)
dataset = version.download("yolov8")


# Función para contar los archivos en un directorio
def contar_imagenes(ruta):
    if os.path.exists(ruta):
        # Cuenta solo los archivos (ignora subcarpetas si las hubiera)
        return len([f for f in os.listdir(ruta) if os.path.isfile(os.path.join(ruta, f))])
    return 0 # Retorna 0 si la carpeta no existe

# Definir las rutas a las carpetas de imágenes
ruta_train = f"{dataset.location}/train/images"
ruta_valid = f"{dataset.location}/valid/images"
ruta_test = f"{dataset.location}/test/images"

# Realizar el conteo
num_train = contar_imagenes(ruta_train)
num_valid = contar_imagenes(ruta_valid)
num_test = contar_imagenes(ruta_test)

# Calcular el total
total_imagenes = num_train + num_valid + num_test

# Imprimir los resultados
print(f"Imágenes de entrenamiento (train): {num_train}")
print(f"Imágenes de validación (valid): {num_valid}")
print(f"Imágenes de prueba (test): {num_test}")
print("-" * 40)
print(f"TOTAL DE IMÁGENES DESCARGADAS: {total_imagenes}")

"""# **# 2. Configuración**"""

# Celda 1: Hiperparámetros estandarizados — Opción B (best practice por arquitectura)
import random
import numpy as np
import torch

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

# --- Protocolo experimental (fijo entre todos los modelos) ---
EPOCHS = 150
BATCH_SIZE = 8
IMGSZ = 640

# --- Optimización (específico de RT-DETR, siguiendo defaults recomendados) ---
OPTIMIZER = 'AdamW'
LR0 = 0.0001
WEIGHT_DECAY = 0.0001
MOMENTUM = 0.9

iterations_per_epoch = num_train / BATCH_SIZE
WARMUP_EPOCHS = 250 / iterations_per_epoch  # equivalente conceptual a WARMUP_ITERS=250 de Faster R-CNN

OUTPUT_DIR = "/content/drive/MyDrive/cacao_experiments"
RUN_NAME = "rtdetr_aug_v1"

print("=== HIPERPARÁMETROS RT-DETR (Opción B) ===")
print(f"Imágenes train: {num_train} | Iter/época: {iterations_per_epoch:.1f}")
print(f"Épocas: {EPOCHS} | Batch: {BATCH_SIZE} | Imgsz: {IMGSZ} | Seed: {SEED}")
print(f"Optimizer: {OPTIMIZER} | LR0: {LR0} | Weight decay: {WEIGHT_DECAY}")
print(f"Warmup épocas: {WARMUP_EPOCHS:.2f}")
print(f"Guardando en: {OUTPUT_DIR}/{RUN_NAME}")

"""# **# 3. Test rapido**"""

# Test rápido de estabilidad — 10 épocas, mismo resto de config
from ultralytics import RTDETR

modelo = RTDETR('rtdetr-l.pt')

resultados_test = modelo.train(
    data=f"{dataset.location}/data.yaml",
    epochs=10,              # <-- solo esto cambia
    batch=BATCH_SIZE,
    imgsz=IMGSZ,
    seed=SEED,
    device=0,
    project=OUTPUT_DIR,
    name="rtdetr_aug_test_lr",  # <-- carpeta separada, no pisa el run real
    optimizer=OPTIMIZER,
    lr0=LR0,
    weight_decay=WEIGHT_DECAY,
    momentum=MOMENTUM,
    warmup_epochs=WARMUP_EPOCHS,
    patience=0,
    mosaic=0.0, mixup=0.0, copy_paste=0.0,
    hsv_h=0.0, hsv_s=0.0, hsv_v=0.0,
    degrees=0.0, translate=0.0, scale=0.0, shear=0.0, perspective=0.0,
    flipud=0.0, fliplr=0.0, bgr=0.0, erasing=0.0,
    auto_augment=None, close_mosaic=0,
)

"""# **# 4. Entrenamiento**"""

# Celda 2: Entrenamiento RT-DETR — AdamW, sin augmentation interno, 150 épocas fijas
print("--- INICIANDO ENTRENAMIENTO RT-DETR (sin augmentation, Opción B) ---")

from ultralytics import RTDETR

modelo = RTDETR('rtdetr-l.pt')

resultados = modelo.train(
    data=f"{dataset.location}/data.yaml",
    epochs=EPOCHS,
    batch=BATCH_SIZE,
    imgsz=IMGSZ,
    seed=SEED,
    device=0,
    project=OUTPUT_DIR,
    name=RUN_NAME,

    # Optimización específica de RT-DETR
    optimizer=OPTIMIZER,
    lr0=LR0,
    weight_decay=WEIGHT_DECAY,
    momentum=MOMENTUM,
    warmup_epochs=WARMUP_EPOCHS,

    # Sin early stopping: metodología exige 150 épocas fijas
    patience=0,

    # Sin augmentation interno (igual criterio que Faster R-CNN)
    mosaic=0.0,
    mixup=0.0,
    copy_paste=0.0,
    hsv_h=0.0,
    hsv_s=0.0,
    hsv_v=0.0,
    degrees=0.0,
    translate=0.0,
    scale=0.0,
    shear=0.0,
    perspective=0.0,
    flipud=0.0,
    fliplr=0.0,
    bgr=0.0,
    erasing=0.0,
    auto_augment=None,
    close_mosaic=0,
)

"""# **# 4. Metricas**

"""

from ultralytics import RTDETR

RUN_NAME = "rtdetr_sin_aug_v1"
OUTPUT_DIR = "/content/drive/MyDrive/cacao_experiments"

best_weights_path = os.path.join(OUTPUT_DIR, RUN_NAME, "weights", "best.pt")
modelo_eval = RTDETR(best_weights_path)

resultados_eval = modelo_eval.val(
    data=f"{dataset.location}/data.yaml",
    split='test',
    device=0,
    project=OUTPUT_DIR,
    name=f"{RUN_NAME}_eval",
)

# --- GLOBAL (directo, sin cálculo manual) ---
map50_global = resultados_eval.box.map50
map50_95_global = resultados_eval.box.map
precision_global = resultados_eval.box.mp   # mean precision
recall_global = resultados_eval.box.mr      # mean recall

n_test_images = resultados_eval.box.nt_per_class.sum() if hasattr(resultados_eval.box, 'nt_per_class') else "ver results"

print(f"map50 (global): {map50_global:.4f}")
print(f"map50_95 (global): {map50_95_global:.4f}")
print(f"precision (global): {precision_global:.4f}")
print(f"recall (global): {recall_global:.4f}")

# --- POR CLASE (directo, ya viene alineado con los nombres reales) ---
import pandas as pd

class_indices = resultados_eval.box.ap_class_index
filas_por_clase = []
for i, cls_idx in enumerate(class_indices):
    p = float(resultados_eval.box.p[i])
    r = float(resultados_eval.box.r[i])
    f1 = 2 * p * r / (p + r + 1e-9)

    filas_por_clase.append({
        'class': modelo_eval.names[cls_idx],
        'map50': round(float(resultados_eval.box.ap50[i]), 4),
        'map50_95': round(float(resultados_eval.box.ap[i]), 4),
        'precision': round(p, 4),
        'recall': round(r, 4),
        'f1': round(f1, 4),
    })

df_por_clase = pd.DataFrame(filas_por_clase)
display(df_por_clase)

import pandas as pd
import os

RUN_NAME = "rtdetr_sin_aug_v1"   # cambiar según sin_aug/con_aug
OUTPUT_DIR = "/content/drive/MyDrive/cacao_experiments"

results_csv = os.path.join(OUTPUT_DIR, RUN_NAME, "results.csv")
df_results = pd.read_csv(results_csv)
df_results.columns = df_results.columns.str.strip()

print("Columnas disponibles:", df_results.columns.tolist())

# La columna de mAP50-95 puede tener distintos nombres según versión de Ultralytics
col_map = 'metrics/mAP50-95(B)' if 'metrics/mAP50-95(B)' in df_results.columns else 'metrics/mAP50-95'

best_idx = df_results[col_map].idxmax()
best_epoch = df_results.loc[best_idx, 'epoch']
best_map = df_results.loc[best_idx, col_map]

print(f"\n✅ Mejor época: {int(best_epoch)}")
print(f"   mAP50-95 en esa época: {best_map:.4f}")

# Mostrar también mAP50, precision, recall en esa misma época, si están disponibles
cols_interes = [c for c in df_results.columns if 'metrics' in c]
print("\nMétricas completas en la mejor época:")
print(df_results.loc[best_idx, cols_interes])

# Confirmar contra args.yaml (por si hubo resume/interrupciones)
import yaml
args_path = os.path.join(OUTPUT_DIR, RUN_NAME, "args.yaml")
with open(args_path) as f:
    args_yaml = yaml.safe_load(f)
print("Épocas totales configuradas:", args_yaml.get('epochs'))
print("Patience configurado:", args_yaml.get('patience'))

import pandas as pd

filas_rtdetr = [
    # --- SIN AUGMENTATION ---
    {'condition': 'sin_aug', 'class': 'GLOBAL',        'test_set_cut': 'CONFIRMAR_CON_EQUIPO', 'n_test_images': 160,
     'precision': 0.7163, 'recall': 0.7886, 'map50': 0.8243, 'map50_95': 0.7597, 'source': 'framework_val', 'notes': ''},
    {'condition': 'sin_aug', 'class': 'Sano',           'test_set_cut': 'CONFIRMAR_CON_EQUIPO', 'n_test_images': 160,
     'precision': 0.9545, 'recall': 0.8736, 'map50': 0.9568, 'map50_95': 0.8685, 'source': 'framework_val', 'notes': ''},
    {'condition': 'sin_aug', 'class': 'C_foraseminis',  'test_set_cut': 'CONFIRMAR_CON_EQUIPO', 'n_test_images': 160,
     'precision': 0.5865, 'recall': 0.6316, 'map50': 0.7038, 'map50_95': 0.6483, 'source': 'framework_val', 'notes': ''},
    {'condition': 'sin_aug', 'class': 'M_perniciosa',   'test_set_cut': 'CONFIRMAR_CON_EQUIPO', 'n_test_images': 160,
     'precision': 0.6421, 'recall': 0.7189, 'map50': 0.8195, 'map50_95': 0.7613, 'source': 'framework_val', 'notes': ''},
    {'condition': 'sin_aug', 'class': 'M_roreri',       'test_set_cut': 'CONFIRMAR_CON_EQUIPO', 'n_test_images': 160,
     'precision': 0.8923, 'recall': 0.8974, 'map50': 0.9051, 'map50_95': 0.8419, 'source': 'framework_val', 'notes': ''},
    {'condition': 'sin_aug', 'class': 'P_palmivora',    'test_set_cut': 'CONFIRMAR_CON_EQUIPO', 'n_test_images': 160,
     'precision': 0.5060, 'recall': 0.8214, 'map50': 0.7362, 'map50_95': 0.6784, 'source': 'framework_val', 'notes': ''},

    # --- CON AUGMENTATION ---
    {'condition': 'con_aug', 'class': 'GLOBAL',        'test_set_cut': 'CONFIRMAR_CON_EQUIPO', 'n_test_images': 204,
     'precision': 0.8766, 'recall': 0.7981, 'map50': 0.8599, 'map50_95': 0.7917, 'source': 'framework_val', 'notes': ''},
    {'condition': 'con_aug', 'class': 'Sano',           'test_set_cut': 'CONFIRMAR_CON_EQUIPO', 'n_test_images': 204,
     'precision': 0.9691, 'recall': 0.8415, 'map50': 0.9272, 'map50_95': 0.8234, 'source': 'framework_val', 'notes': ''},
    {'condition': 'con_aug', 'class': 'C_foraseminis',  'test_set_cut': 'CONFIRMAR_CON_EQUIPO', 'n_test_images': 204,
     'precision': 0.8832, 'recall': 0.6333, 'map50': 0.7495, 'map50_95': 0.7105, 'source': 'framework_val', 'notes': ''},
    {'condition': 'con_aug', 'class': 'M_perniciosa',   'test_set_cut': 'CONFIRMAR_CON_EQUIPO', 'n_test_images': 204,
     'precision': 0.9025, 'recall': 0.9474, 'map50': 0.9789, 'map50_95': 0.9063, 'source': 'framework_val', 'notes': ''},
    {'condition': 'con_aug', 'class': 'M_roreri',       'test_set_cut': 'CONFIRMAR_CON_EQUIPO', 'n_test_images': 204,
     'precision': 0.9613, 'recall': 0.7297, 'map50': 0.8461, 'map50_95': 0.7695, 'source': 'framework_val', 'notes': ''},
    {'condition': 'con_aug', 'class': 'P_palmivora',    'test_set_cut': 'CONFIRMAR_CON_EQUIPO', 'n_test_images': 204,
     'precision': 0.6671, 'recall': 0.8387, 'map50': 0.7977, 'map50_95': 0.7487, 'source': 'framework_val', 'notes': ''},
]

df_rtdetr = pd.DataFrame(filas_rtdetr)
display(df_rtdetr)

from google.colab import files
df_rtdetr.to_csv('metrics_rtdetr.csv', index=False)
files.download('metrics_rtdetr.csv')