# -*- coding: utf-8 -*-
"""yolo26n.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_RznxZ6in7t6vddDadTbMCRyy0rVTYE4

### 1. Conectar con Google Drive
Primero, montamos Google Drive para poder guardar los resultados del entrenamiento en la carpeta especificada.
"""

from google.colab import drive
import os

drive.mount('/content/drive')

# Crear la carpeta de destino en Drive si no existe
drive_path = '/content/drive/MyDrive/cacao_final'
os.makedirs(drive_path, exist_ok=True)
print(f"Los resultados se guardarán en: {drive_path}")

"""### 2. Instalar Librerías
Instalamos `ultralytics` para el modelo YOLO y `roboflow` para descargar el dataset.
"""

!pip install -q ultralytics roboflow

"""### 3. Descargar el Dataset de Roboflow
**IMPORTANTE:** Reemplaza `'TU_API_KEY_AQUI'` con tu API key real de Roboflow antes de ejecutar esta celda.
"""

!pip install roboflow


from roboflow import Roboflow
rf = Roboflow(api_key="Ik6eEYG0FuBkzGPLZSDK")
project = rf.workspace("ariels-workspace-b3hov").project("dataset_cocoa_disease_aug_ahorasi")

version = project.version(1)
dataset = version.download("yolo26")


print(f"Dataset descargado en: {dataset.location}")

"""### 4. Anular Albumentations de Ultralytics
Para asegurar que el pipeline de Albumentations nativo de Ultralytics no aplique ningún filtro (como Blur, MedianBlur, etc.), parcheamos la clase para que simplemente devuelva las imágenes intactas.
"""

import ultralytics.data.augment

# Clase para parchear Albumentations y evitar que altere las imágenes
class NoAlbumentations:
    def __init__(self, *args, **kwargs):
        pass
    def __call__(self, labels):
        # Simplemente devuelve el diccionario de labels intacto
        return labels

# Inyectamos nuestro parche en la librería
ultralytics.data.augment.Albumentations = NoAlbumentations
print("Albumentations ha sido desactivado exitosamente (Parche actualizado).")

"""### 5. Configurar y Entrenar el Modelo
Iniciamos el entrenamiento desactivando absolutamente todas las augmentaciones nativas en los argumentos y configurando los hiperparámetros solicitados. El entrenamiento se guardará directamente en tu Google Drive.
"""

from ultralytics import YOLO
import os

# Inicializar el modelo YOLO nano (YOLOv26 nano)
model = YOLO('yolo26n.pt')

# Ruta al archivo de configuración de datos (data.yaml)
data_yaml_path = os.path.join(dataset.location, 'data.yaml')

# Entrenar el modelo
results = model.train(
    data=data_yaml_path,
    project=drive_path,       # Carpeta principal en Drive
    name='train_aug_nano',      # Nombre del experimento
    epochs=150,               # 150 épocas
    imgsz=640,                # Tamaño de imagen de 640
    batch=16,                 # Batch size de 16
    seed=0,                   # Semilla de 0 para reproducibilidad
    optimizer='AdamW',        # Optimizador AdamW
    weight_decay=1e-4,        # Weight decay de 1e-4
    lr0=0.001,                # Learning rate inicial de 0.001
    save=True,                # Guardar el modelo (guarda best.pt por defecto)

    # --- DESACTIVACIÓN TOTAL DE AUGMENTATION ---
    auto_augment='',          # Desactiva auto_augment enviando un string vacío en lugar de False
    hsv_h=0.0,
    hsv_s=0.0,
    hsv_v=0.0,
    degrees=0.0,
    translate=0.0,
    scale=0.0,
    shear=0.0,
    perspective=0.0,
    flipud=0.0,
    fliplr=0.0,
    mosaic=0.0,
    mixup=0.0,
    copy_paste=0.0,
    erasing=0.0
)

print("¡Entrenamiento completado y guardado en Drive!")

import pandas as pd
import os
from ultralytics import YOLO

# Ruta al mejor modelo guardado durante el entrenamiento
best_model_path = os.path.join(drive_path, 'train_aug_nano', 'weights', 'best.pt')

print(f"Cargando el modelo desde: {best_model_path}")
best_model = YOLO(best_model_path)

# Ejecutar validación para obtener las métricas detalladas
print("Evaluando el modelo en el conjunto de validación...")
metrics = best_model.val()

# Definir el mapeo de nombres de clases deseado por el usuario
# Asumimos que class_indices contiene los índices numéricos originales (0, 1, 2, 3, 4)
# y que estos corresponden directamente a las clases que el usuario desea renombrar.
new_class_names_map = {
    0: "Healthy",
    1: "Corncob disease (Carmenta foraseminis)",
    2: "Witches’ broom (Moniliophthora perniciosa)",
    3: "Moniliasis (Moniliophthora roreri)",
    4: "Phytophthora (Phytophthora palmivora)"
}

# Extraer las métricas por clase y aplicar el nuevo mapeo de nombres
class_indices = metrics.ap_class_index
# Usar el mapeo definido para obtener los nombres de las clases en el orden correcto
renamed_class_names = [new_class_names_map.get(idx, f"Unknown Class {idx}") for idx in class_indices]
map50_95_per_class = metrics.box.map  # Array con el mAP50-95 por clase evaluada
map50_per_class = metrics.box.map50

# Crear un DataFrame con los resultados
metrics_df = pd.DataFrame({
    'Clase': renamed_class_names, # Usamos los nombres renombrados aquí
    'mAP50': map50_per_class,
    'mAP50-95': map50_95_per_class
})

# Mostrar los resultados en Colab
print("\nMétricas por clase (nombres actualizados):")
display(metrics_df)

# Guardar en la ruta del Drive
csv_path = os.path.join(drive_path, 'train_aug_nano', 'metricas_por_clase.csv')
metrics_df.to_csv(csv_path, index=False)
print(f"\nMétricas guardadas exitosamente en: {csv_path}")


"""### 8. Generar CSV de Métricas con Formato Específico
Este fragmento de código extrae las métricas globales y por clase del objeto `metrics_corrected` y las organiza en un DataFrame de pandas con el formato especificado, incluyendo los nombres de clase abreviados. Finalmente, guarda este DataFrame como un archivo CSV en Google Drive.
"""

import pandas as pd
import os
from ultralytics import YOLO # Añadido para que YOLO esté disponible

# Asegurarse de que 'drive_path' esté disponible del contexto anterior
# (Se asume que la celda d5a8f64d ya fue ejecutada)

# --- Inclusión de la lógica de la celda 28b3ae9f para definir metrics_corrected ---
# Ruta CORREGIDA al mejor modelo guardado durante el entrenamiento
best_model_path_corrected = os.path.join(drive_path, 'train_aug_small', 'weights', 'best.pt')

print(f"Cargando el modelo desde la ruta corregida: {best_model_path_corrected}")
best_model_corrected = YOLO(best_model_path_corrected)

# Ejecutar validación para obtener las métricas detalladas con el modelo corregido
print("Evaluando el modelo en el conjunto de validación con la ruta corregida...")
metrics_corrected = best_model_corrected.val()
# ----------------------------------------------------------------------------------

# Mapeo de índices de clase a nombres cortos requeridos en el CSV
csv_class_names_map = {
    0: "Sano",
    1: "C_foraseminis",
    2: "M_perniciosa",
    3: "M_roreri",
    4: "P_palmivora"
}

# 1. Crear el DataFrame base con las columnas fijas
data = {
    'model': ['YOLO26n'] * 6,
    'family': ['YOLO26n'] * 6,
    'condition': ['no_aug'] * 6, # Basado en el nombre del experimento 'train_no_aug_nano'
    'class': ['GLOBAL', 'Sano', 'C_foraseminis', 'M_perniciosa', 'M_roreri', 'P_palmivora'],
    'test_set_cut': [''] * 6,
    'n_test_images': [''] * 6,
    'precision': [''] * 6,
    'recall': [''] * 6,
    'map50': [''] * 6,
    'map50_95': [''] * 6,
    'source': [''] * 6,
    'notes': [''] * 6
}
metrics_csv_df = pd.DataFrame(data)

# 2. Extraer y poblar métricas globales
global_precision = metrics_corrected.box.mp
global_recall = metrics_corrected.box.mr
global_map50 = metrics_corrected.box.map50
global_map50_95 = metrics_corrected.box.map

# Contar imágenes directamente desde el directorio de validación para evitar errores de atributo
val_images_dir = '/content/dataset_cocoa_disease_aug_ahorasi-1/valid/images'
if os.path.exists(val_images_dir):
    n_test_images_global = len([f for f in os.listdir(val_images_dir) if f.lower().endswith(('.jpg', '.jpeg', '.png'))])
else:
    n_test_images_global = 321 # Fallback basado en los logs de validación

metrics_csv_df.loc[0, 'test_set_cut'] = 'roboflow_export_no_aug'
metrics_csv_df.loc[0, 'n_test_images'] = n_test_images_global
metrics_csv_df.loc[0, 'precision'] = f"{global_precision:.4f}"
metrics_csv_df.loc[0, 'recall'] = f"{global_recall:.4f}"
metrics_csv_df.loc[0, 'map50'] = f"{global_map50:.4f}"
metrics_csv_df.loc[0, 'map50_95'] = f"{global_map50_95:.4f}"
metrics_csv_df.loc[0, 'source'] = 'framework_val'
metrics_csv_df.loc[0, 'notes'] = '' # Dejar en blanco a menos que haya notas específicas

# 3. Extraer y poblar métricas por clase
for i, class_idx in enumerate(metrics_corrected.ap_class_index):
    csv_class_name = csv_class_names_map.get(class_idx, f"Unknown Class {class_idx}")
    row_idx = metrics_csv_df[metrics_csv_df['class'] == csv_class_name].index

    if not row_idx.empty:
        metrics_csv_df.loc[row_idx[0], 'test_set_cut'] = 'roboflow_export_no_aug'
        metrics_csv_df.loc[row_idx[0], 'n_test_images'] = n_test_images_global # Mismo para todas las clases
        metrics_csv_df.loc[row_idx[0], 'precision'] = f"{metrics_corrected.box.p[i]:.4f}"
        metrics_csv_df.loc[row_idx[0], 'recall'] = f"{metrics_corrected.box.r[i]:.4f}"
        metrics_csv_df.loc[row_idx[0], 'map50'] = f"{metrics_corrected.box.ap50[i]:.4f}"
        metrics_csv_df.loc[row_idx[0], 'map50_95'] = f"{metrics_corrected.box.ap[i]:.4f}"
        metrics_csv_df.loc[row_idx[0], 'source'] = 'framework_val'
        metrics_csv_df.loc[row_idx[0], 'notes'] = '' # Dejar en blanco a menos que haya notas específicas

# 4. Guardar el DataFrame como CSV
csv_output_filename = 'metrics_yolo26s_aug.csv'
csv_output_path = os.path.join(drive_path, csv_output_filename)
metrics_csv_df.to_csv(csv_output_path, index=False, float_format='%.4f') # Asegurar formato decimal con punto

print(f"\nCSV de métricas generado y guardado en: {csv_output_path}")
display(metrics_csv_df)

"""### 6. Eliminar Datasets en Caché
Este paso elimina el directorio del dataset descargado por Roboflow para liberar espacio o para asegurar que se descargue una versión nueva en el futuro.
"""

import shutil
import os

# La ruta del dataset se obtuvo de la ejecución anterior de Roboflow
dataset_cache_path = "/content/dataset_cocoa_disease-1"

if os.path.exists(dataset_cache_path):
    shutil.rmtree(dataset_cache_path)
    print(f"El dataset en caché '{dataset_cache_path}' ha sido eliminado exitosamente.")
else:
    print(f"El directorio '{dataset_cache_path}' no existe o ya fue eliminado.")